### ISSUE TITLE
Scratches

### ISSUE THREAD

**Issue by royreddy** [robinhowlett/handycapper#2]
wondering if you would include Scratches from each race to the list of ToDos

**Comment by robinhowlett** [comment]
Scratches are already being parsed and stored correctly in the database:

![image](https://user-images.githubusercontent.com/906722/40632033-ebd59724-629f-11e8-983b-7506e7684bb8.png)

and are also surfaced in [the REST API's JSON output](https://github.com/robinhowlett/handycapper/blob/master/docs/json-design.md):

![image](https://user-images.githubusercontent.com/906722/40632054-16f7d28c-62a0-11e8-8530-9f3620d7a5a1.png)

They are not in either the desktop app UI or the Excel export - do you mean adding them one or both of those?

**Comment by royreddy** [comment]
excellent & elaborate answer. 
I found the DB docs page_(read: this side of the keyboard, my error for not looking sooner)_
& now I see the Scratches in the DB.
Ok to Close this as user error and non-issue.
